# bare minimal
name: Report Changes
on: push
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: output
        run: |
          echo 'All: ${{ steps.file_changes.outputs.files}}'
          echo 'Modified: ${{ steps.file_changes.outputs.files_modified}}'
          echo 'Added: ${{ steps.file_changes.outputs.files_added}}'
          echo 'Deleted: ${{ steps.file_changes.outputs.files_removed}}'
