name: Word2MD
on: 
  push:
    paths:
      - '**/*.puml'
  

jobs:
  diagrams:
    name: convert diagrams
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source 
      uses: actions/checkout@v1
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
    - name: UML files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: make output dir
      run: mkdir -p output
    - name: Process diagrams
      uses: Timmy/plantuml-action@v1
      with:
        args: '-tpng -o output $UML_FILES'
    - name: Push Local Changes
      uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
      with: 
          commit_user_name: "Leonard Rosenthol"
          commit_user_email: "leonardr@lazerware.com"
          commit_author: "Leonard Rosenthol <leonardr@lazerware.com>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
