name: PlantUML
on: 
  push:
    paths:
      - '**/*.puml'
  

jobs:
  diagrams:
    name: convert diagrams
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".puml"
    steps:
    - name: Checkout Source 
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Get changed UML files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | tr " " "\n" | grep ${{ env.UML_FILES }} )"
    - name: UML files considered echo output
      run: |
        echo ${{ steps.getfile.outputs.files }}
    - name: make output dir
      run: mkdir -p output
    - name: Process diagrams
      uses: cloudbees/plantuml-github-action@master
      with:
        args: -v -tpng -o output ${{ steps.getfile.outputs.files }}
    - name: Push Local Changes
      uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
      with: 
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "leonardr@lazerware.com"
          commit_author: "Leonard Rosenthol <actions@github.com>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
