# bare minimal
name: Word2MD
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
    - name: Changed Files Exporter
      id: file_changes
      uses: trilom/file-changes-action@v1.2.3

    - name: output
      run: |
        echo 'Modified: ${{ steps.file_changes.outputs.files_modified}}'
        echo 'Added: ${{ steps.file_changes.outputs.files_added}}'
        echo 'Deleted: ${{ steps.file_changes.outputs.files_removed}}'

      # use core for regular stuff and latex for PDF
      # - uses: docker://pandoc/core:2.9
      #   with:
      #     args: --output=output/result.pdf ${{ env.FILELIST }}
      # - uses: actions/upload-artifact@master
      #   with:
      #     name: output
      #     path: output
  